# Generated by Django 5.2.9 on 2026-01-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('contact_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('cnf_password', models.CharField(max_length=10)),
            ],
        ),
    ]
